server:
  port: 28081
spring:
  application:
    name: ${ServiceId}


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EurekaIpAddr}/eureka/ #eureka注册地址

info:
  app:
    name: ${ServiceId}
    ip: 
    port: ${server.port}
    active: Development
  company.name: www.QiaFan.com
  build.artifactId:
  build.version:


