server:
  port: 28081
spring:
  application:
    name: login-server-01


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:28080/eureka/ #eureka注册地址

#service 的名称
ServiceId: login-server

info:
  app:
    name: ${ServiceId}
    ip: 
    port: ${server.port}
    active: Development
  company.name: www.QiaFan.com
  build.artifactId:
  build.version:


