server:
  port: 28080 #端口

eureka:
  instance:
    hostname: eureka-server-01 #eureka服务实例
    prefer-ip-address: true #注册自己的ip
  client:
    register-with-eureka: false #不拔自己注册在服务上
    fetch-registry: false #不从eureka来获取服务的注册信息
    service-url:
        defaultZone: http://localhost:${server.port}/eureka/ #eureka注册地址

##service 的名称
#ServiceId: login-server

info:
  app:
    name: ${ServiceId}
    ip:
    port: ${server.port}
    active: Development
  company.name: www.QiaFan.com
  build.artifactId:
  build.version:



