server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:

      defaultZone: http://${EurekaIpAddr}/eureka #eureka注册地址


zuul:
  routes:
    login:
      path: /login/**
      serviceId: login-server
info:
  app:
    name: ${spring.application.name}
    ip:
    port: ${server.port}
    active: Development
  company.name: www.QiaFan.com
  build.artifactId:
  build.version:

