server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EurekaIpAddr}/eureka #eureka注册地址

    #匹配/github/直接重定向到https://github.com/
#    github:
#      path: /github/**
#      url: https://github.com/
info:
  app:
    name: ${ServiceId}
    ip: 
    port: ${server.port}
    active: Development
  company.name: www.QiaFan.com
  build.artifactId:
  build.version:

